### ISSUE TITLE
Vault Extension fails if module is loaded but not in PSModulePath

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/SecretManagement#103]
## Steps to reproduce
1. Save a module to a separate directory outside PSModulePath (e.g. $HOME/test/SecretManagement.KeePass)
1. Import the module
1. `Register-SecretVault -ModuleName 'SecretManagement.KeePass'`

## Expected Behavior
Register-SecretVault will detect the loaded module and prioritize that and configure it as the registered path

## Actual Behavior
Register-SecretVault fails to detect the loaded module and fails because it does not find it in psmoduleapth
![image](https://user-images.githubusercontent.com/15258962/108645107-8910d500-7466-11eb-8dbc-e9162d8f3773.png)

## Workaround
Specify the full path to the module manifest with -ModuleName, however this is not desired in testing situations where you are testing the loading of the module in the most common method, its name.

**Comment by PaulHigin** [comment]
This is by design and follows how PowerShell module loading works.  If you do not specify a module path in `-ModuleName` parameter then the module is searched for in $PSModulePath.

SecretManagement can't know if an extension vault module has been updated during development, and so always loads with `-Force` to be safe.  This means the module is always re-loaded over an old imported module.  This works for script based modules.

Unfortunately a binary module cannot be re-loaded because .Net does not allow a new version of a module to be re-loaded into the same appdomain, and a new PowerShell session must be created.  But this has been a limitation of PowerShell modules since the beginning.

**Comment by JustinGrote** [comment]
@PaulHigin Let me clarify:

If I have a module at C:\temp\SecretManagement.KeePass, and I import that module *manually* prior to running register-secretvault with `import-module`, if I do `Register-SecretVault -ModuleName  'SecretManagement.KeePass'`, `Register-SecretVault` should check **if an existing module is already loaded** and reload with force **that module at that specific path** rather than doing a PSModulePath search.

If no existing module is imported at the time of `Register-SecretVault` invocation, then it should follow the process that you state.

This causes me a problem if I'm testing a module with pester or using a "nightly" copy of a module not saved in psmodulepath, I *have* to put it in psmodulepath in order to work work whereas if this fix was in place, I could import the module from an arbitrary location and continue to use `Register-SecretVault` as expected.

**Comment by PaulHigin** [comment]
I don't think your example above is correct because it assumes the user intent is to always use an existing loaded module path, and I don't believe this is true.  During testing a user may want to import from PSModulePath by omitting the module path, and this alternative behavior would be confusing.  Script modules support reloading, and I can imagine a user wanting to load from multiple locations during testing.  I think it is best to keep the current behavior since it adheres to PowerShell module path finding and is something most users would expect.

**Comment by JustinGrote** [comment]
@PaulHigin I think it's fair to mirror the `Import-Module` behavior.
