### ISSUE TITLE
Designdoc - Verbose implementation.

### ISSUE THREAD

**Issue by itfranck** [PowerShell/SecretManagement#75]
I was looking at the changelog and saw something was done for verbose.

Can't the flag be passed down normally through the calling cmdlet ?
For instance, 

```
Get-Secret -Name 'SuperSecret' -AsPlainText -vault MyVault -Verbose
```

I would expect that verbose flag to be passed down to the implementing module, not a flag that need to be defined in VaultParameters. (And following that logic, it should be possible to pass the `-debug` flag in the same manner). 

With #66 , it seems that I need to unregister the vault, then register it again with verbose, then unregister / re-register it again when done. It feels like we're going the long way around.

**Comment by PaulHigin** [comment]
Yes, the `-Verbose` flag is now passed to the extension vault cmdlets as part of the `AdditionalParameters` parameters.  This is done automatically, you do not have to add them to the VaultParameters field when registering an extension vault.

However, you do have to look for the `Verbose` parameter in `AdditionalParameters` in your extension vault cmdlets, and set `$VerbosePreference` accordingly so that verbose output is written.

**Comment by itfranck** [comment]
@PaulHigin Yup, I see that now and it work as expected.

Maybe it should be added in the [DesignDoc](https://github.com/PowerShell/SecretManagement/blob/master/Docs/DesignDoc.md) then ?


I edited the title of this ticket to reflect that need.

**Comment by PaulHigin** [comment]
Fixed.
